version: '3.9'

services:
  web:
    build: .
    container_name: django_web
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - 8000

  nginx:
    image: nginx:1.25-alpine
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
